### ISSUE TITLE
Feature request: add replace image function

### ISSUE THREAD

**Issue by Zhwt** [nguyenthenguyen/docx#19]
Hi, thank you for your awesome work!

It would be nice to have a `ReplaceImage()` function, the function could be like the following:

```go
func ReplaceImage(oldFilePath, newFilePath)
```

In which the `oldFilePath` is the image file name inside `word/media`, and the `newFilePath` is the file path we want to replace into.

And so far I've figured out there will be 3 things to do to replace an image:

1. Compress the image file and copy it into `word/media/...` and overwrite the old file.
2. Modify the `<Relationship Id="..." Type="..." Target="media/image1.png"/>` line according to the new image file format.
3. Register image file type to `[Content_Types].xml` if it doesn't contain the corresponding file type.

**Comment by nguyenthenguyen** [comment]
@Zhwt Sorry, at this time, I can not add more features to this library. Could you please help to create a merge request for this feature?

**Comment by Zhwt** [comment]
@nguyenthenguyen Sure, but I'm afraid I don't have much time at this moment, I'll look into this maybe some days later.

**Comment by nguyenthenguyen** [comment]
Closed #21
