### ISSUE TITLE
文档替换失败

### ISSUE THREAD

**Issue by chowyu12** [nguyenthenguyen/docx#22]
文档替换失败：
origin docx:
![image](https://user-images.githubusercontent.com/81024796/176578526-eb1ad86c-d52c-41ef-86ed-a7fbd31201bf.png)

code:

![image](https://user-images.githubusercontent.com/81024796/176578623-16c863b7-a7e4-4cbe-b3d4-57b5d0e42378.png)

result:
![image](https://user-images.githubusercontent.com/81024796/176578731-d57338f6-f8e1-4015-ae4b-df0d9e2e561b.png)

**Comment by nguyenthenguyen** [comment]
Hi @chowyu12 

Because this lib just replaces the text in XML files, maybe the replacement text in your Word file is broken by the XML tag, could you please help to try [this](https://github.com/nguyenthenguyen/docx/issues/12#issuecomment-594243367)
